version: "3"

services:
  testcafe:
    environment:
      USER_NAME: ${USER_NAME}
    image: testcafe/testcafe
    volumes:
      - ./test:/usr/src/
      - ./screenshots:/screenshots
    command: >
      "chromium:headless --no-sandbox"
      /usr/src/*
